"""Versioned citation store (ARCHITECTURE.md Sections 4, 9, principle Section 2.4).

Every regulation string is a constant, effective-date-versioned and scoped
`(rule_id, text, effective_from, effective_to, source, last_verified)`. The
engine selects the version valid at the case's *relevant date*, not today — a
2023 denial gets the 8-year moratorium; a post-1-April-2024 denial gets 60
months. Citations are injected into templates, never generated by an LLM.

No autonomous mutation (Section 2.5): entries flagged `provisional` await human
legal ratification via the regulatory-freshness agent (Section 12).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Any, Optional


@dataclass(frozen=True)
class Citation:
    rule_id: str
    text: str
    effective_from: date
    effective_to: Optional[date]  # None == still in force
    source: str
    last_verified: date
    value: Any = None            # numeric payload where the rule is a number
    provisional: bool = False    # True == not yet ratified by a human reviewer

    def in_force_on(self, on: date) -> bool:
        if on < self.effective_from:
            return False
        if self.effective_to is not None and on > self.effective_to:
            return False
        return True


class CitationStore:
    def __init__(self, citations: list[Citation]):
        self._by_rule: dict[str, list[Citation]] = {}
        for c in citations:
            self._by_rule.setdefault(c.rule_id, []).append(c)
        for versions in self._by_rule.values():
            versions.sort(key=lambda c: c.effective_from)

    def resolve(self, rule_id: str, relevant_date: date) -> Citation:
        """The version of `rule_id` valid at `relevant_date`."""
        versions = self._by_rule.get(rule_id)
        if not versions:
            raise KeyError(f"no citation for rule {rule_id!r}")
        matches = [c for c in versions if c.in_force_on(relevant_date)]
        if not matches:
            raise KeyError(
                f"no version of {rule_id!r} in force on {relevant_date.isoformat()}"
            )
        return max(matches, key=lambda c: c.effective_from)

    def has_exact_source(self, source: str) -> bool:
        """V3 support: is this regulation string a known constant?"""
        return any(
            c.source == source for versions in self._by_rule.values() for c in versions
        )

    def has_exact_text(self, text: str) -> bool:
        return any(
            c.text == text for versions in self._by_rule.values() for c in versions
        )


# --- Seed store (health / PED ground) ---------------------------------------
# The 2024 circular is the anchor citation of Section 6.1. Pre-2024 entries are
# provisional pending legal re-verification (honest per Section 2.5).

_MASTER_CIRCULAR_2024 = (
    "IRDAI Master Circular on Health Insurance Business, "
    "IRDAI/HLT/CIR/MISC/77/05/2024, dated 29 May 2024"
)

SEED_CITATIONS: list[Citation] = [
    Citation(
        rule_id="MORATORIUM",
        text=(
            "After 60 months of continuous coverage, no health insurance claim "
            "shall be contestable on grounds of non-disclosure or "
            "misrepresentation, save for established fraud."
        ),
        effective_from=date(2024, 4, 1),
        effective_to=None,
        source=_MASTER_CIRCULAR_2024,
        last_verified=date(2024, 6, 1),
        value=60,
    ),
    Citation(
        rule_id="MORATORIUM",
        text=(
            "Under the pre-1-April-2024 framework the moratorium period after "
            "which non-disclosure could not be raised was 96 months (8 years) "
            "of continuous coverage."
        ),
        effective_from=date(2016, 7, 1),
        effective_to=date(2024, 3, 31),
        source="IRDAI (Health Insurance) Regulations, 2016 — moratorium (superseded)",
        last_verified=date(2024, 6, 1),
        value=96,
        provisional=True,
    ),
    Citation(
        rule_id="PED_WAITING_CAP",
        text=(
            "The waiting period for pre-existing diseases shall not exceed 36 "
            "months of continuous coverage."
        ),
        effective_from=date(2024, 4, 1),
        effective_to=None,
        source=_MASTER_CIRCULAR_2024,
        last_verified=date(2024, 6, 1),
        value=36,
    ),
    Citation(
        rule_id="PED_WAITING_CAP",
        text=(
            "Under the pre-1-April-2024 framework the waiting period for "
            "pre-existing diseases could extend up to 48 months of continuous "
            "coverage."
        ),
        effective_from=date(2016, 7, 1),
        effective_to=date(2024, 3, 31),
        source="IRDAI (Health Insurance) Regulations, 2016 — PED waiting (superseded)",
        last_verified=date(2024, 6, 1),
        value=48,
        provisional=True,
    ),
    Citation(
        rule_id="MATERIALITY",
        text=(
            "Material facts are those expressly sought in the proposal form; a "
            "matter not asked gives rise to no duty of disclosure."
        ),
        effective_from=date(2017, 4, 1),
        effective_to=None,
        source="IRDAI (Protection of Policyholders' Interests) Regulations — materiality standard",
        last_verified=date(2024, 6, 1),
        provisional=True,
    ),
    Citation(
        rule_id="BURDEN_OF_PROOF",
        text=(
            "The burden of proving deliberate suppression of a material fact, "
            "and the insured's knowledge of it at the time of proposal, lies on "
            "the insurer."
        ),
        effective_from=date(2017, 4, 1),
        effective_to=None,
        source="IRDAI (Protection of Policyholders' Interests) Regulations — burden of proof",
        last_verified=date(2024, 6, 1),
        provisional=True,
    ),
]


def default_store() -> CitationStore:
    return CitationStore(SEED_CITATIONS)
